# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sr.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
import datetime
import sqlite3 as s

db = s.connect("./database/store.db") 
cdb = db.cursor()
cdb.execute("SELECT DISTINCT product_subcat FROM raw_inventory")
dd = cdb.fetchall()
bad_chars = [';', "'", ')', "(", ","]
cat = [] 
for i in range(len(dd)):
    nd = ''.join((filter(lambda i: i not in bad_chars, dd[i])))
    cat.append(nd)
DateTime = datetime.datetime.now()


class Ui_billy(object):
    def setupUi(self, bill):
        bill.setObjectName("bill")
        bill.setFixedSize(769, 633)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/main.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        bill.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(bill)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 10, 441, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 30, 771, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(10, 90, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Rod")
        font.setPointSize(12)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.contact = QtWidgets.QLabel(self.centralwidget)
        self.contact.setGeometry(QtCore.QRect(420, 90, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Rod")
        font.setPointSize(12)
        self.contact.setFont(font)
        self.contact.setObjectName("contact")
        self.sname = QtWidgets.QLineEdit(self.centralwidget)
        self.sname.setGeometry(QtCore.QRect(150, 90, 261, 31))
        self.sname.setObjectName("sname")
        self.scontact = QtWidgets.QLineEdit(self.centralwidget)
        self.scontact.setGeometry(QtCore.QRect(590, 90, 141, 31))
        self.scontact.setObjectName("scontact")
        self.contact_2 = QtWidgets.QLabel(self.centralwidget)
        self.contact_2.setGeometry(QtCore.QRect(340, 50, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Rod")
        font.setPointSize(12)
        self.contact_2.setFont(font)
        self.contact_2.setObjectName("contact_2")
        self.date = QtWidgets.QLineEdit(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(390, 50, 111, 31))
        self.date.setObjectName("date")
        self.date.setText('%s/%s/%s' % (DateTime.day, DateTime.month, DateTime.year))
        self.contact_3 = QtWidgets.QLabel(self.centralwidget)
        self.contact_3.setGeometry(QtCore.QRect(520, 50, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Rod")
        font.setPointSize(12)
        self.contact_3.setFont(font)
        self.contact_3.setObjectName("contact_3")
        self.time = QtWidgets.QLineEdit(self.centralwidget)
        self.time.setGeometry(QtCore.QRect(570, 50, 91, 31))
        self.time.setObjectName("time")
        self.contact_4 = QtWidgets.QLabel(self.centralwidget)
        self.contact_4.setGeometry(QtCore.QRect(10, 50, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Rod")
        font.setPointSize(12)
        self.contact_4.setFont(font)
        self.contact_4.setObjectName("contact_4")
        self.invno = QtWidgets.QLineEdit(self.centralwidget)
        self.invno.setGeometry(QtCore.QRect(170, 50, 141, 31))
        self.invno.setObjectName("invno")
        self.name_2 = QtWidgets.QLabel(self.centralwidget)
        self.name_2.setGeometry(QtCore.QRect(10, 140, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Rod")
        font.setPointSize(12)
        self.name_2.setFont(font)
        self.name_2.setObjectName("name_2")
        self.name_3 = QtWidgets.QLabel(self.centralwidget)
        self.name_3.setGeometry(QtCore.QRect(530, 140, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Rod")
        font.setPointSize(12)
        self.name_3.setFont(font)
        self.name_3.setObjectName("name_3")
        self.name_4 = QtWidgets.QLabel(self.centralwidget)
        self.name_4.setGeometry(QtCore.QRect(370, 180, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Rod")
        font.setPointSize(12)
        self.name_4.setFont(font)
        self.name_4.setObjectName("name_4")
        self.iqt = QtWidgets.QSpinBox(self.centralwidget)
        self.iqt.setGeometry(QtCore.QRect(510, 180, 61, 31))
        self.iqt.setMaximum(999999999)
        self.iqt.setObjectName("iqt")
        self.resetall = QtWidgets.QPushButton(self.centralwidget)
        self.resetall.setGeometry(QtCore.QRect(590, 540, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Kozuka Mincho Pro B")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.resetall.setFont(font)
        self.resetall.setObjectName("resetall")
        self.icat = QtWidgets.QComboBox(self.centralwidget)
        self.icat.setGeometry(QtCore.QRect(350, 140, 171, 31))
        self.icat.setObjectName("icat")
        self.icat.addItem(" ")
        for t in range(len(cat)):
            self.icat.addItem(cat[t])
        self.name_5 = QtWidgets.QLabel(self.centralwidget)
        self.name_5.setGeometry(QtCore.QRect(10, 260, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Rod")
        font.setPointSize(12)
        self.name_5.setFont(font)
        self.name_5.setObjectName("name_5")
        self.remarks = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.remarks.setGeometry(QtCore.QRect(100, 270, 231, 71))
        self.remarks.setObjectName("remarks")
        self.name_6 = QtWidgets.QLabel(self.centralwidget)
        self.name_6.setGeometry(QtCore.QRect(380, 260, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Rod")
        font.setPointSize(12)
        self.name_6.setFont(font)
        self.name_6.setObjectName("name_6")
        self.name_8 = QtWidgets.QLabel(self.centralwidget)
        self.name_8.setGeometry(QtCore.QRect(10, 360, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Rod")
        font.setPointSize(12)
        self.name_8.setFont(font)
        self.name_8.setObjectName("name_8")
        self.issuedby = QtWidgets.QLineEdit(self.centralwidget)
        self.issuedby.setGeometry(QtCore.QRect(200, 360, 191, 31))
        self.issuedby.setObjectName("issuedby")
        self.add2db = QtWidgets.QPushButton(self.centralwidget)
        self.add2db.setGeometry(QtCore.QRect(10, 540, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Rod")
        font.setPointSize(16)
        self.add2db.setFont(font)
        self.add2db.setStyleSheet("color: rgb(170, 0, 0);\n"
"background-color: rgb(255, 255, 127);")
        self.add2db.setObjectName("add2db")
        self.add2db.clicked.connect(self.menufunction)
        self.iid = QtWidgets.QLineEdit(self.centralwidget)
        self.iid.setGeometry(QtCore.QRect(90, 140, 111, 31))
        self.iid.setObjectName("iid")
        self.name_10 = QtWidgets.QLabel(self.centralwidget)
        self.name_10.setGeometry(QtCore.QRect(210, 140, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Rod")
        font.setPointSize(12)
        self.name_10.setFont(font)
        self.name_10.setObjectName("name_10")
        self.iname = QtWidgets.QLineEdit(self.centralwidget)
        self.iname.setGeometry(QtCore.QRect(110, 180, 251, 31))
        self.iname.setObjectName("iname")
        self.name_11 = QtWidgets.QLabel(self.centralwidget)
        self.name_11.setGeometry(QtCore.QRect(380, 220, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Rod")
        font.setPointSize(12)
        self.name_11.setFont(font)
        self.name_11.setObjectName("name_11")
        self.icat2 = QtWidgets.QLineEdit(self.centralwidget)
        self.icat2.setGeometry(QtCore.QRect(560, 140, 181, 31))
        self.icat2.setFrame(True)
        self.icat2.setClearButtonEnabled(False)
        self.icat2.setObjectName("icat2")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 120, 771, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.name_9 = QtWidgets.QLabel(self.centralwidget)
        self.name_9.setGeometry(QtCore.QRect(10, 180, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Rod")
        font.setPointSize(12)
        self.name_9.setFont(font)
        self.name_9.setObjectName("name_9")
        self.name_12 = QtWidgets.QLabel(self.centralwidget)
        self.name_12.setGeometry(QtCore.QRect(580, 180, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Rod")
        font.setPointSize(12)
        self.name_12.setFont(font)
        self.name_12.setObjectName("name_12")
        self.po1 = QtWidgets.QSpinBox(self.centralwidget)
        self.po1.setGeometry(QtCore.QRect(690, 180, 71, 31))
        self.po1.setMaximum(999999999)
        self.po1.setObjectName("po1")
        self.csname = QtWidgets.QLineEdit(self.centralwidget)
        self.csname.setGeometry(QtCore.QRect(220, 440, 181, 31))
        self.csname.setObjectName("csname")
        self.name_13 = QtWidgets.QLabel(self.centralwidget)
        self.name_13.setGeometry(QtCore.QRect(10, 440, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Rod")
        font.setPointSize(12)
        self.name_13.setFont(font)
        self.name_13.setObjectName("name_13")
        self.amount = QtWidgets.QLineEdit(self.centralwidget)
        self.amount.setGeometry(QtCore.QRect(570, 220, 161, 31))
        self.amount.setObjectName("amount")
        self.name_14 = QtWidgets.QLabel(self.centralwidget)
        self.name_14.setGeometry(QtCore.QRect(10, 480, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Rod")
        font.setPointSize(12)
        self.name_14.setFont(font)
        self.name_14.setObjectName("name_14")
        self.cscontact = QtWidgets.QLineEdit(self.centralwidget)
        self.cscontact.setGeometry(QtCore.QRect(250, 480, 141, 31))
        self.cscontact.setObjectName("cscontact")
        self.tnc = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.tnc.setGeometry(QtCore.QRect(460, 270, 231, 71))
        self.tnc.setObjectName("tnc")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 410, 771, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.name_15 = QtWidgets.QLabel(self.centralwidget)
        self.name_15.setGeometry(QtCore.QRect(480, 440, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Rod")
        font.setPointSize(12)
        self.name_15.setFont(font)
        self.name_15.setObjectName("name_15")
        self.csref = QtWidgets.QLineEdit(self.centralwidget)
        self.csref.setGeometry(QtCore.QRect(540, 470, 141, 31))
        self.csref.setObjectName("csref")
        bill.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(bill)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 769, 21))
        self.menubar.setObjectName("menubar")
        bill.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(bill)
        self.statusbar.setObjectName("statusbar")
        bill.setStatusBar(self.statusbar)
        self.resetall.clicked.connect(self.invno.clear)
        self.resetall.clicked.connect(self.time.clear)
        self.resetall.clicked.connect(self.sname.clear)
        self.resetall.clicked.connect(self.scontact.clear)
        self.resetall.clicked.connect(self.iid.clear)
        self.resetall.clicked.connect(self.icat2.clear)
        self.resetall.clicked.connect(self.iname.clear)
        self.resetall.clicked.connect(self.iqt.clear)
        self.resetall.clicked.connect(self.po1.clear)
        self.resetall.clicked.connect(self.amount.clear)
        self.resetall.clicked.connect(self.remarks.clear)
        self.resetall.clicked.connect(self.tnc.clear)
        self.resetall.clicked.connect(self.issuedby.clear)
        self.resetall.clicked.connect(self.csname.clear)
        self.resetall.clicked.connect(self.cscontact.clear)
        self.resetall.clicked.connect(self.csref.clear)
        self.retranslateUi(bill)
        QtCore.QMetaObject.connectSlotsByName(bill)
        

    def retranslateUi(self, bill):
        _translate = QtCore.QCoreApplication.translate
        bill.setWindowTitle(_translate("bill", "STOCK REGISTRY MODULE"))
        self.label.setText(_translate("bill", "STOCK REGISTRY MODULE"))
        self.name.setText(_translate("bill", "SUPPLIER NAME"))
        self.contact.setText(_translate("bill", "SUPPLIER CONTACT"))
        self.contact_2.setText(_translate("bill", "DATE"))
        self.contact_3.setText(_translate("bill", "TIME"))
        self.contact_4.setText(_translate("bill", "INVOICE RECIEPT"))
        self.name_2.setText(_translate("bill", "Item ID"))
        self.name_3.setText(_translate("bill", "OR "))
        self.name_4.setText(_translate("bill", "Item Quantity"))
        self.resetall.setText(_translate("bill", "RESET ALL"))
        self.name_5.setText(_translate("bill", "Remarks: "))
        self.name_6.setText(_translate("bill", "T & C *"))
        self.name_8.setText(_translate("bill", "ENTERED BY NAME/ID "))
        self.add2db.setText(_translate("bill", "ADD TO DATABASE"))
        self.name_10.setText(_translate("bill", "ITEM CATEGORY"))
        self.name_11.setText(_translate("bill", "TOTAL PAYED AMOUNT"))
        self.icat2.setPlaceholderText(_translate("bill", "write your Custom Category..."))
        self.name_9.setText(_translate("bill", "Item Name"))
        self.name_12.setText(_translate("bill", "Price of 1: "))
        self.name_13.setText(_translate("bill", "Courier Service Name"))
        self.name_14.setText(_translate("bill", "Courier Service Contact"))
        self.name_15.setText(_translate("bill", "Courier Receipt Reference "))
        
        
    def menufunction(self, action):
        self.time.setText('%s:%s:%s' % (DateTime.hour, DateTime.minute, DateTime.second))
        v = self.invno.text() #its primary key, so must be unique always
        v = str(v)
        v1 = self.date.text()
        v1 = str(v1)
        v2 = self.time.text()
        v3 = self.sname.text()
        v4 = self.scontact.text()
        v41 = self.iid.text()
        #v5 = str(self.icat.currentText())
        if(self.icat.currentText() == " "):
            v5 = str(self.icat2.text())
        else:
            v5 = str(self.icat.currentText())
        v6 = self.iname.text()
        v7 = int(self.iqt.value())
        v8 = str(self.po1.value())
        v88 = self.amount.text()
        v9 = self.remarks.toPlainText()
        v99 = self.tnc.toPlainText()
        v11 = self.issuedby.text()
        v12 = self.csref.text()
        v13 = self.csname.text()
        v14 = self.cscontact.text()
        
        rv = v1+'/'+v
        self.invno.setText(str(rv))
        

        if(v6 != "" and (str(self.icat.currentIndex()) != "0" or self.icat2.text() != "")):
            cdb.execute("insert into raw_inventory(invoice_receipt, date, time, supplier_name, supplier_contact, product_id, product_subcat, product_name, stock, mrp, total_payed_amount, remarks, tnc, entered_by, courier_service_reference, courier_service_name, courier_service_contact) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);",(rv, v1, v2, v3, v4, v41,v5, v6, v7, v8, v88, v9, v99, v11, v12, v13, v14))
            db.commit()
            #for showing popup of successfull entry in database
            from PyQt5.QtWidgets import QMessageBox
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("Successfully entered")
            msg.setInformativeText('Database updated')
            msg.setWindowTitle("DONE !!!")
            msg.exec_()    
            
    
        else:
            from PyQt5.QtWidgets import QMessageBox
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("Please enter ALL Item Details")
            msg.setInformativeText('Null values can not be entered in Database')
            msg.setWindowTitle("Oopssiee")
            msg.exec_()
            
            

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    bill = QtWidgets.QMainWindow()
    ui = Ui_billy()
    ui.setupUi(bill)
    bill.show()
    sys.exit(app.exec_())
